- name: DEVELOPING CATALOGUE APPLICATION
  hosts: catalogue
  become: yes
  tasks:

  - name: SETTING UP NODEJS
    ansible.builtin.shell:  curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: INSTALLING NODEJS APPLICATION
    ansible.builtin.yum:
      name: nodejs 
      state: present

  - name: CHECKING WHETHER USER EXISTS OR NOT
    become: yes
    ansible.builtin.command: id roboshop
    register: user
    ignore_errors: true

  - when user.rc !=0
    name: CREATING USER
    ansible.builtin.user:
      name: roboshop

  - name: CHECK FOLDER EXISTS OR NOT
    ansible.builtin.stat: 
      path: /app
    register: directory
    ignore_errors: true
    



      