- name: DEVELOPING CATALOGUE APPLICATION
  hosts: catalogue
  tasks:

  - name: SETTING UP NODEJS
    ansible.builtin.shell:  curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: INSTALLING NODEJS APPLICATION
    ansible.builtin.yum:
      name: nodejs 
      state: present

  - name: CHECKING WHETHER USER EXISTS OR NOT
    become: yes
    ansible.builtin.command: id roboshop
    register: user
    ignore_errors: true
